//
//  QuoteLibrary.swift
//  Motivation
//
//  Created by Leonardo Aurelio on 28/10/2025.
//

import SwiftUI

// Shared quotes array accessible from any file in the app target.
// You can add more quotes here; keep them as comma-separated Swift string literals.
let quotes: [String] = [
    
        // Enero (1-31)
        "You have power over your mind — not outside events. — Marcus Aurelius",
        "Waste no more time arguing what a good man should be. Be one. — Marcus Aurelius",
        "The best revenge is not to be like your enemy. — Marcus Aurelius",
        "Very little is needed to make a happy life. — Marcus Aurelius",
        "Accept whatever comes to you woven in the pattern of your destiny. — Marcus Aurelius",
        "The soul becomes dyed with the colour of its thoughts. — Marcus Aurelius",
        "Everything we hear is an opinion, not a fact. — Marcus Aurelius",
        "Nowhere can man find a quieter retreat than in his own soul. — Marcus Aurelius",
        "Life is short — the fruit of this life is a good character. — Marcus Aurelius",
        "Be tolerant with others and strict with yourself. — Marcus Aurelius",
        "The universe is change; our life is what our thoughts make it. — Marcus Aurelius",
        "Look well into thyself; there is a source of strength. — Marcus Aurelius",
        "Nothing happens to anyone that they can't endure. — Marcus Aurelius",
        "The first rule is to keep an untroubled spirit. — Marcus Aurelius",
        "Do every act of your life as if it were your last. — Marcus Aurelius",
        "If it is not right, do not do it. If it is not true, do not say it. — Marcus Aurelius",
        "Now is the time to learn truly who you are. — Marcus Aurelius",
        "Let men see, let them know, a real man. — Marcus Aurelius",
        "You are a little soul carrying around a corpse. — Epictetus",
        "Don't explain your philosophy. Embody it. — Epictetus",
        "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
        "First say to yourself what you would be; and then do what you have to do. — Epictetus",
        "No man is free who is not master of himself. — Epictetus",
        "Circumstances don't make the man, they only reveal him. — Epictetus",
        "It's not what happens to you, but how you react that matters. — Epictetus",
        "Only the educated are free. — Epictetus",
        "If you want to improve, be content to be thought foolish. — Epictetus",
        "He who laughs at himself never runs out of things to laugh at. — Epictetus",
        "Freedom is the only worthy goal in life. — Epictetus",
        "Attach yourself to what is spiritually superior. — Epictetus",
        "Practice yourself, for heaven's sake, in little things. — Epictetus",
        
        // Febrero (32-59)
        "We suffer more often in imagination than in reality. — Seneca",
        "Luck is what happens when preparation meets opportunity. — Seneca",
        "It is not that we have a short time to live, but that we waste a lot of it. — Seneca",
        "Difficulties strengthen the mind, as labor does the body. — Seneca",
        "He who is brave is free. — Seneca",
        "As long as you live, keep learning how to live. — Seneca",
        "Begin at once to live, and count each day as a separate life. — Seneca",
        "All cruelty springs from weakness. — Seneca",
        "The whole future lies in uncertainty: live immediately. — Seneca",
        "No person has the power to have everything they want, but it is in their power not to want what they don't have. — Seneca",
        "We are not given a short life, but we make it short. — Seneca",
        "A gem cannot be polished without friction, nor a man perfected without trials. — Seneca",
        "If you really want to escape the things that harass you, what you're needing is not to be in a different place but to be a different person. — Seneca",
        "Hang on to your youthful enthusiasms — you'll be able to use them better when you're older. — Seneca",
        "Enjoy present pleasures in such a way as not to injure future ones. — Seneca",
        "We often suffer more from apprehension than from reality. — Seneca",
        "The greatest remedy for anger is delay. — Seneca",
        "What need is there to weep over parts of life? The whole of it calls for tears. — Seneca",
        "He suffers more than necessary, who suffers before it is necessary. — Seneca",
        "While we wait for life, life passes. — Seneca",
        "It does not matter what you bear, but how you bear it. — Seneca",
        "Life is very short and anxious for those who forget the past, neglect the present, and fear the future. — Seneca",
        "No one can lose what they've already let go of. — Seneca",
        "Time heals what reason cannot. — Seneca",
        "Leisure without books is death. — Seneca",
        "Ignorance is the cause of fear. — Seneca",
        "True happiness is to enjoy the present. — Seneca",
        "We are more often frightened than hurt; we suffer more in imagination than reality. — Seneca",
        
        // Marzo (60-90)
        "The key is to keep company only with people who uplift you. — Epictetus",
        "Don't seek for everything to happen as you wish it would. — Epictetus",
        "It is impossible for a man to learn what he thinks he already knows. — Epictetus",
        "If you wish to be a writer, write. — Epictetus",
        "Don't seek events to happen as you wish, but wish them to happen as they do. — Epictetus",
        "Progress is not achieved by luck or accident, but by working on yourself daily. — Epictetus",
        "The greater the difficulty, the more glory in surmounting it. — Epictetus",
        "He is a wise man who does not grieve for the things which he has not. — Epictetus",
        "When you are offended at any man's fault, turn to yourself. — Epictetus",
        "Only the wise are free, and only the virtuous are wise. — Epictetus",
        "First learn the meaning of what you say, and then speak. — Epictetus",
        "Know, first, who you are, and then adorn yourself accordingly. — Epictetus",
        "If you desire to be good, begin by believing that you are wicked. — Epictetus",
        "We have two ears and one mouth so we can listen twice as much as we speak. — Epictetus",
        "It is not events that disturb people, it is their judgments concerning them. — Epictetus",
        "Practice yourself, for heaven's sake, in little things. — Epictetus",
        "He who is making progress has learned that desire is for things good. — Epictetus",
        "The good or ill of a man lies within his own will. — Epictetus",
        "No great thing is created suddenly. — Epictetus",
        "In every affair consider what precedes and what follows. — Epictetus",
        "Don't just say you have read books. Show that through them you have learned to think better. — Epictetus",
        "What upsets people is not things themselves, but their judgments about these things. — Epictetus",
        "Do not try to seem wise to others. — Epictetus",
        "Preach not to others what they should eat, but eat as becomes you. — Epictetus",
        "An educated person is able to withstand and endure hardships. — Epictetus",
        "No one is free who is not master of himself. — Epictetus",
        "Be careful to leave your sons well instructed rather than rich. — Epictetus",
        "It takes more than just a good looking body. You've got to have the heart and soul to go with it. — Epictetus",
        "When you close your doors, and make darkness within, remember never to say that you are alone. — Epictetus",
        "The condition and characteristic of an uninstructed person is this: he never expects benefit from himself. — Epictetus",
        "When you are about to undertake a project, consider what precedes and follows. — Epictetus",
        
        // Abril (91-120)
        "The obstacle in the path becomes the path. — Marcus Aurelius",
        "Our actions may be impeded, but there can be no impeding our intentions. — Marcus Aurelius",
        "A man's worth is no greater than his ambitions. — Marcus Aurelius",
        "Dig within. Within is the wellspring of good. — Marcus Aurelius",
        "Loss is nothing else but change, and change is Nature's delight. — Marcus Aurelius",
        "Reject your sense of injury and the injury itself disappears. — Marcus Aurelius",
        "The only wealth which you will keep forever is the wealth you have given away. — Marcus Aurelius",
        "No random actions, none not based on underlying principles. — Marcus Aurelius",
        "To live happily is an inward power of the soul. — Marcus Aurelius",
        "Anger cannot be dishonest. — Marcus Aurelius",
        "Because your own strength is unequal to the task, do not assume that it is beyond the powers of man. — Marcus Aurelius",
        "Despise not death, but welcome it, for nature wills it like all else. — Marcus Aurelius",
        "He who lives in harmony with himself lives in harmony with the universe. — Marcus Aurelius",
        "How much time he gains who does not look to see what his neighbor says or does. — Marcus Aurelius",
        "I have often wondered how it is that every man loves himself more than all the rest of men. — Marcus Aurelius",
        "In a little while you will have forgotten everything; in a little while everything will have forgotten you. — Marcus Aurelius",
        "Let not your mind run on what you lack as much as on what you have already. — Marcus Aurelius",
        "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too. — Marcus Aurelius",
        "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason. — Marcus Aurelius",
        "No carelessness in your actions. No confusion in your words. — Marcus Aurelius",
        "Nothing has such power to broaden the mind as the ability to investigate systematically. — Marcus Aurelius",
        "Objective judgment, now, at this very moment. — Marcus Aurelius",
        "Pass through this brief patch of time in harmony with nature. — Marcus Aurelius",
        "Remember that very little is needed to make a happy life. — Marcus Aurelius",
        "Stop drifting. You are not going to re-read your brief notes. — Marcus Aurelius",
        "That which is not good for the swarm, neither is it good for the bee. — Marcus Aurelius",
        "The art of living is more like wrestling than dancing. — Marcus Aurelius",
        "The mind is the master of every kind of fortune; itself acts in both ways, being the cause of its own happiness and misery. — Marcus Aurelius",
        "The secret of all victory lies in the organization of the non-obvious. — Marcus Aurelius",
        "The universe is transformation; our life is what our thoughts make it. — Marcus Aurelius",
        
        // Mayo (121-150)
        "You are not compelled to form any opinion about this matter. — Marcus Aurelius",
        "The mind adapts and converts to its own purposes the obstacle to our acting. — Marcus Aurelius",
        "Take away your opinion, and there is taken away the complaint. — Marcus Aurelius",
        "The best answer to anger is silence. — Marcus Aurelius",
        "Receive without pride, let go without attachment. — Marcus Aurelius",
        "Think of the life you have lived until now as over and, as a dead man, see what's left as a bonus. — Marcus Aurelius",
        "Time is a river of passing events, and strong is its current. — Marcus Aurelius",
        "Whatever anyone does or says, I must be good. — Marcus Aurelius",
        "When you arise in the morning, think of what a precious privilege it is to be alive. — Marcus Aurelius",
        "Where a man can live, he can also live well. — Marcus Aurelius",
        "You always own the option of having no opinion. — Marcus Aurelius",
        "Your life is what your thoughts make it. — Marcus Aurelius",
        "A wrongdoer is often a man who has left something undone. — Marcus Aurelius",
        "Be content to seem what you really are. — Marcus Aurelius",
        "Because a thing seems difficult for you, do not think it impossible. — Marcus Aurelius",
        "Blame no one. Set people right, if you can. — Marcus Aurelius",
        "Death smiles at us all; all we can do is smile back. — Marcus Aurelius",
        "Each day provides its own gifts. — Marcus Aurelius",
        "Everything that exists is in a manner the seed of that which will be. — Marcus Aurelius",
        "He who does not know what the world is, does not know where he is. — Marcus Aurelius",
        "If any man can convince me and bring home to me that I do not think or act right, I will gladly change. — Marcus Aurelius",
        "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius",
        "Let no act be done without a purpose. — Marcus Aurelius",
        "Never esteem anything as of advantage to you that will make you break your word. — Marcus Aurelius",
        "No man is happy who does not think himself so. — Marcus Aurelius",
        "Nothing happens to any man that he is not formed by nature to bear. — Marcus Aurelius",
        "Our life is what our thoughts make it. — Marcus Aurelius",
        "Poverty is the mother of crime. — Marcus Aurelius",
        "Remember this—that there is a proper dignity and proportion to be observed. — Marcus Aurelius",
        "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius",
        
        // Junio (151-180)
        "Confine yourself to the present. — Marcus Aurelius",
        "The present is all that they can give up, since that is all you have. — Marcus Aurelius",
        "Each of us lives only now, this brief instant. — Marcus Aurelius",
        "Give yourself a gift—the present moment. — Marcus Aurelius",
        "In the life of a man, his time is but a moment. — Marcus Aurelius",
        "Let future things disturb those who may be affected by them. — Marcus Aurelius",
        "Live as if you were living for the second time. — Marcus Aurelius",
        "Nothing belongs to me but the present. — Marcus Aurelius",
        "The present moment is all you ever have. — Marcus Aurelius",
        "Today I escaped anxiety. Or no, I discarded it, because it was within me. — Marcus Aurelius",
        "Do not act as if you had ten thousand years to throw away. — Marcus Aurelius",
        "For the present is the only thing of which a man can be deprived. — Marcus Aurelius",
        "He who lives in the present lives in eternity. — Marcus Aurelius",
        "How many together with whom I came into the world are already gone out of it. — Marcus Aurelius",
        "It is not the future that weighs on you, but the present. — Marcus Aurelius",
        "Let not your mind be burdened by the past or the future. — Marcus Aurelius",
        "Live each day as if it were your last. — Marcus Aurelius",
        "No longer talk about the kind of man that a good man ought to be, but be such. — Marcus Aurelius",
        "The present time is of the highest importance. — Marcus Aurelius",
        "Though you break your heart, men will go on as before. — Marcus Aurelius",
        "Tomorrow is nothing, today is too late; the good lived yesterday. — Marcus Aurelius",
        "A man must stand erect, not be kept erect by others. — Marcus Aurelius",
        "Be like the cliff against which the waves continually break. — Marcus Aurelius",
        "Death is a release from the impressions of the senses. — Marcus Aurelius",
        "Everything that happens happens as it should. — Marcus Aurelius",
        "He who fears death either fears the loss of sensation or a different kind of sensation. — Marcus Aurelius",
        "If it is not right, do not do it; if it is not true, do not say it. — Marcus Aurelius",
        "It is in your power to withdraw yourself whenever you desire. — Marcus Aurelius",
        "Let opinion be taken away, and no man will think himself wronged. — Marcus Aurelius",
        "Never let the future disturb you. — Marcus Aurelius",
        
        // Julio (181-210)
        "Waste no more time arguing about what a good man should be. Be one. — Marcus Aurelius",
        "Virtue is the only good. — Seneca",
        "The good man is the friend of the gods. — Epictetus",
        "Virtue is nothing else than right reason. — Seneca",
        "The wise man is content with himself. — Seneca",
        "Virtue is its own reward. — Seneca",
        "A good character is the only guarantee of everlasting happiness. — Seneca",
        "Wisdom allows nothing to be good that will not be so forever. — Seneca",
        "No evil is honorable; but death is honorable; therefore death is not evil. — Seneca",
        "The greatest wealth is a poverty of desires. — Seneca",
        "The first step in a person's salvation is knowledge of their sin. — Seneca",
        "We should every night call ourselves to an account. — Seneca",
        "A good mind possesses a kingdom. — Seneca",
        "The greatest remedy for anger is delay. — Seneca",
        "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it. — Seneca",
        "He who does not prevent a crime when he can, encourages it. — Seneca",
        "It is quality rather than quantity that matters. — Seneca",
        "No man was ever wise by chance. — Seneca",
        "The mind that is anxious about future events is miserable. — Seneca",
        "Wherever there is a human being, there is an opportunity for a kindness. — Seneca",
        "A man's as miserable as he thinks he is. — Seneca",
        "He who is brave is free. — Seneca",
        "It is a rough road that leads to the heights of greatness. — Seneca",
        "No man can have a peaceful life who thinks too much about lengthening it. — Seneca",
        "The willing, destiny guides them. The unwilling, destiny drags them. — Seneca",
        "Wisdom does not show itself so much in precept as in life. — Seneca",
        "A gem cannot be polished without friction, nor a man perfected without trials. — Seneca",
        "He who has great power should use it lightly. — Seneca",
        "It is not the man who has too little, but the man who craves more, that is poor. — Seneca",
        "No evil propensity of the human heart is so powerful that it may not be subdued by discipline. — Seneca",
        
        // Agosto (211-240)
        "Let your desires be ruled by reason. — Cicero",
        "Freedom is not procured by a full enjoyment of what is desired. — Epictetus",
        "It is not the man who has too little, but the man who craves more, that is poor. — Seneca",
        "If you desire to be good, begin by believing that you are wicked. — Epictetus",
        "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
        "The greater the difficulty, the more glory in surmounting it. — Epictetus",
        "He is a wise man who does not grieve for the things which he has not. — Epictetus",
        "First say to yourself what you would be; and then do what you have to do. — Epictetus",
        "If you want to improve, be content to be thought foolish. — Epictetus",
        "No great thing is created suddenly. — Epictetus",
        "The key is to keep company only with people who uplift you. — Epictetus",
        "We have two ears and one mouth so we can listen twice as much as we speak. — Epictetus",
        "Don't just say you have read books. Show that through them you have learned to think better. — Epictetus",
        "Do not try to seem wise to others. — Epictetus",
        "Know, first, who you are, and then adorn yourself accordingly. — Epictetus",
        "It is impossible for a man to learn what he thinks he already knows. — Epictetus",
        "The condition and characteristic of an uninstructed person is this: he never expects benefit from himself. — Epictetus",
        "Only the educated are free. — Epictetus",
        "When you are offended at any man's fault, turn to yourself. — Epictetus",
        "He who is making progress has learned that desire is for things good. — Epictetus",
        "The good or ill of a man lies within his own will. — Epictetus",
        "Practice yourself, for heaven's sake, in little things. — Epictetus",
        "An educated person is able to withstand and endure hardships. — Epictetus",
        "Be careful to leave your sons well instructed rather than rich. — Epictetus",
        "He who laughs at himself never runs out of things to laugh at. — Epictetus",
        "It takes more than just a good looking body. You've got to have the heart and soul to go with it. — Epictetus",
        "When you close your doors, and make darkness within, remember never to say that you are alone. — Epictetus",
        "In every affair consider what precedes and what follows. — Epictetus",
        "Don't seek events to happen as you wish, but wish them to happen as they do. — Epictetus",
        "First learn the meaning of what you say, and then speak. — Epictetus",
        
        // Septiembre (241-270)
        "Accept the things to which fate binds you. — Marcus Aurelius",
        "Don't demand that things happen as you wish, but wish that they happen as they do. — Epictetus",
        "Fate leads the willing and drags along the reluctant. — Seneca",
        "Everything that happens happens as it should. — Marcus Aurelius",
        "If you are distressed by anything external, the pain is not due to the thing itself. — Marcus Aurelius",
        "What stands in the way becomes the way. — Marcus Aurelius",
        "The universe is change; our life is what our thoughts make it. — Marcus Aurelius",
        "Loss is nothing else but change, and change is Nature's delight. — Marcus Aurelius",
        "Reject your sense of injury and the injury itself disappears. — Marcus Aurelius",
        "No random actions, none not based on underlying principles. — Marcus Aurelius",
        "He who lives in harmony with himself lives in harmony with the universe. — Marcus Aurelius",
        "Look back over the past, with its changing empires that rose and fell. — Marcus Aurelius",
        "Never let the future disturb you. You will meet it with the same weapons of reason. — Marcus Aurelius",
        "Objective judgment, now, at this very moment. — Marcus Aurelius",
        "Pass through this brief patch of time in harmony with nature. — Marcus Aurelius",
        "The art of living is more like wrestling than dancing. — Marcus Aurelius",
        "The mind is the master of every kind of fortune. — Marcus Aurelius",
        "The universe is transformation; our life is what our thoughts make it. — Marcus Aurelius",
        "Think of the life you have lived until now as over and, as a dead man, see what's left as a bonus. — Marcus Aurelius",
        "Time is a river of passing events, and strong is its current. — Marcus Aurelius",
        "Whatever anyone does or says, I must be good. — Marcus Aurelius",
        "When you arise in the morning, think of what a precious privilege it is to be alive. — Marcus Aurelius",
        "Where a man can live, he can also live well. — Marcus Aurelius",
        "You always own the option of having no opinion. — Marcus Aurelius",
        "Your life is what your thoughts make it. — Marcus Aurelius",
        "Blame no one. Set people right, if you can. — Marcus Aurelius",
        "Death smiles at us all; all we can do is smile back. — Marcus Aurelius",
        "Each day provides its own gifts. — Marcus Aurelius",
        "Everything that exists is in a manner the seed of that which will be. — Marcus Aurelius",
        "If any man can convince me and bring home to me that I do not think or act right, I will gladly change. — Marcus Aurelius",
        
        // Octubre (271-300)
        "Think of yourself as dead. You have lived your life. Now take what's left and live it properly. — Marcus Aurelius",
        "Let us prepare our minds as if we'd come to the very end of life. — Seneca",
        "I cannot escape death, but at least I can escape the fear of it. — Epictetus",
        "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius",
        "Death is a release from the impressions of the senses. — Marcus Aurelius",
        "He who fears death either fears the loss of sensation or a different kind of sensation. — Marcus Aurelius",
        "In a little while you will have forgotten everything; in a little while everything will have forgotten you. — Marcus Aurelius",
        "Let not your mind be burdened by the past or the future. — Marcus Aurelius",
        "No man can have a peaceful life who thinks too much about lengthening it. — Seneca",
        "The present is all that they can give up, since that is all you have. — Marcus Aurelius",
        "Today I escaped anxiety. Or no, I discarded it, because it was within me. — Marcus Aurelius",
        "Do not act as if you had ten thousand years to throw away. — Marcus Aurelius",
        "For the present is the only thing of which a man can be deprived. — Marcus Aurelius",
        "How many together with whom I came into the world are already gone out of it. — Marcus Aurelius",
        "It is not the future that weighs on you, but the present. — Marcus Aurelius",
        "Live each day as if it were your last. — Marcus Aurelius",
        "No longer talk about the kind of man that a good man ought to be, but be such. — Marcus Aurelius",
        "The present time is of the highest importance. — Marcus Aurelius",
        "Though you break your heart, men will go on as before. — Marcus Aurelius",
        "Tomorrow is nothing, today is too late; the good lived yesterday. — Marcus Aurelius",
        "A man must stand erect, not be kept erect by others. — Marcus Aurelius",
        "Be like the cliff against which the waves continually break. — Marcus Aurelius",
        "Everything that happens happens as it should. — Marcus Aurelius",
        "If it is not right, do not do it; if it is not true, do not say it. — Marcus Aurelius",
        "It is in your power to withdraw yourself whenever you desire. — Marcus Aurelius",
        "Let opinion be taken away, and no man will think himself wronged. — Marcus Aurelius",
        "Never let the future disturb you. — Marcus Aurelius",
        "No man is happy who does not think himself so. — Marcus Aurelius",
        "Nothing happens to any man that he is not formed by nature to bear. — Marcus Aurelius",
        "Our life is what our thoughts make it. — Marcus Aurelius",
        
        // Noviembre (301-330)
        "Wisdom is the only freedom. — Seneca",
        "To know how to grow old is the master work of wisdom. — Henri-Frédéric Amiel",
        "The wise man is free from restraint. — Musonius Rufus",
        "Wisdom allows nothing to be good that will not be so forever. — Seneca",
        "No evil is honorable; but death is honorable; therefore death is not evil. — Seneca",
        "The greatest wealth is a poverty of desires. — Seneca",
        "The first step in a person's salvation is knowledge of their sin. — Seneca",
        "We should every night call ourselves to an account. — Seneca",
        "A good mind possesses a kingdom. — Seneca",
        "The greatest remedy for anger is delay. — Seneca",
        "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it. — Seneca",
        "He who does not prevent a crime when he can, encourages it. — Seneca",
        "It is quality rather than quantity that matters. — Seneca",
        "No man was ever wise by chance. — Seneca",
        "The mind that is anxious about future events is miserable. — Seneca",
        "Wherever there is a human being, there is an opportunity for a kindness. — Seneca",
        "A man's as miserable as he thinks he is. — Seneca",
        "He who is brave is free. — Seneca",
        "It is a rough road that leads to the heights of greatness. — Seneca",
        "No man can have a peaceful life who thinks too much about lengthening it. — Seneca",
        "The willing, destiny guides them. The unwilling, destiny drags them. — Seneca",
        "Wisdom does not show itself so much in precept as in life. — Seneca",
        "A gem cannot be polished without friction, nor a man perfected without trials. — Seneca",
        "He who has great power should use it lightly. — Seneca",
        "It is not the man who has too little, but the man who craves more, that is poor. — Seneca",
        "No evil propensity of the human heart is so powerful that it may not be subdued by discipline. — Seneca",
        "The wise man is content with himself. — Seneca",
        "Virtue is its own reward. — Seneca",
        "A good character is the only guarantee of everlasting happiness. — Seneca",
        "Virtue is nothing else than right reason. — Seneca",
        
        // Diciembre (331-365)
        "He who lives in harmony with himself lives in harmony with the universe. — Marcus Aurelius",
        "Peace is in staying silent when you have nothing useful to say. — Musonius Rufus",
        "Nothing is so conducive to greatness of mind as the ability to examine systematically. — Seneca",
        "The best revenge is not to be like your enemy. — Marcus Aurelius",
        "Very little is needed to make a happy life. — Marcus Aurelius",
        "Accept whatever comes to you woven in the pattern of your destiny. — Marcus Aurelius",
        "The soul becomes dyed with the colour of its thoughts. — Marcus Aurelius",
        "Everything we hear is an opinion, not a fact. — Marcus Aurelius",
        "Nowhere can man find a quieter retreat than in his own soul. — Marcus Aurelius",
        "Life is short — the fruit of this life is a good character. — Marcus Aurelius",
        "Be tolerant with others and strict with yourself. — Marcus Aurelius",
        "The universe is change; our life is what our thoughts make it. — Marcus Aurelius",
        "Look well into thyself; there is a source of strength. — Marcus Aurelius",
        "Nothing happens to anyone that they can't endure. — Marcus Aurelius",
        "The first rule is to keep an untroubled spirit. — Marcus Aurelius",
        "Do every act of your life as if it were your last. — Marcus Aurelius",
        "If it is not right, do not do it. If it is not true, do not say it. — Marcus Aurelius",
        "Now is the time to learn truly who you are. — Marcus Aurelius",
        "Let men see, let them know, a real man. — Marcus Aurelius",
        "You are a little soul carrying around a corpse. — Epictetus",
        "Don't explain your philosophy. Embody it. — Epictetus",
        "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
        "First say to yourself what you would be; and then do what you have to do. — Epictetus",
        "No man is free who is not master of himself. — Epictetus",
        "Circumstances don't make the man, they only reveal him. — Epictetus",
        "It's not what happens to you, but how you react that matters. — Epictetus",
        "Only the educated are free. — Epictetus",
        "If you want to improve, be content to be thought foolish. — Epictetus",
        "He who laughs at himself never runs out of things to laugh at. — Epictetus",
        "Freedom is the only worthy goal in life. — Epictetus",
        "Attach yourself to what is spiritually superior. — Epictetus",
        "Practice yourself, for heaven's sake, in little things. — Epictetus",
        "We suffer more often in imagination than in reality. — Seneca",
        "Luck is what happens when preparation meets opportunity. — Seneca",
        "It is not that we have a short time to live, but that we waste a lot of it. — Seneca"
    ]

struct QuoteLibrary: View {
    var body: some View {
        VStack(alignment: .leading) {
            Text("Quote Library")
                .font(.largeTitle)
                .bold()
                .padding(20)

            List {
                ForEach(quotes, id: \.self) { quote in
                    Text(quote)
                        .padding(.vertical, 4)
                }
            }
//            .scrollContentBackground(.hidden)
//            .background(Color.clear)
//            .listStyle(.insetGrouped)
        }
    }
}

#Preview {
    QuoteLibrary()
}
