import SwiftUI

let quotesES: [String] = [
    // Enero (1-31)
    "Tienes poder sobre tu mente, no sobre los acontecimientos externos. — Marco Aurelio",
    "No malgastes más tiempo discutiendo cómo debe ser un buen hombre. Sé uno. — Marco Aurelio",
    "La mejor venganza es no ser como tu enemigo. — Marco Aurelio",
    "Muy poco se necesita para tener una vida feliz. — Marco Aurelio",
    "Acepta lo que venga a ti tejido en el patrón de tu destino. — Marco Aurelio",
    "El alma se tiñe del color de sus pensamientos. — Marco Aurelio",
    "Todo lo que oímos es una opinión, no un hecho. — Marco Aurelio",
    "En ninguna parte puede el hombre encontrar un retiro más tranquilo que en su propia alma. — Marco Aurelio",
    "La vida es corta; el fruto de esta vida es un buen carácter. — Marco Aurelio",
    "Sé tolerante con los demás y estricto contigo mismo. — Marco Aurelio",
    "El universo es cambio; nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",
    "Mira bien dentro de ti mismo; allí hay una fuente de fortaleza. — Marco Aurelio",
    "Nada le sucede a nadie que no pueda soportar. — Marco Aurelio",
    "La primera regla es mantener un espíritu sereno. — Marco Aurelio",
    "Realiza cada acto de tu vida como si fuera el último. — Marco Aurelio",
    "Si no es correcto, no lo hagas. Si no es verdad, no lo digas. — Marco Aurelio",
    "Ahora es el momento de aprender verdaderamente quién eres. — Marco Aurelio",
    "Deja que los hombres vean, que conozcan a un hombre verdadero. — Marco Aurelio",
    "Eres un alma pequeña que carga un cadáver. — Epicteto",
    "No expliques tu filosofía. Encárnala. — Epicteto",
    "La riqueza no consiste en tener grandes posesiones, sino en tener pocos deseos. — Epicteto",
    "Primero dite a ti mismo lo que serías; y luego haz lo que tienes que hacer. — Epicteto",
    "Ningún hombre es libre si no es dueño de sí mismo. — Epicteto",
    "Las circunstancias no hacen al hombre, solo lo revelan. — Epicteto",
    "No es lo que te sucede, sino cómo reaccionas lo que importa. — Epicteto",
    "Solo los educados son libres. — Epicteto",
    "Si quieres mejorar, estate dispuesto a que te consideren tonto. — Epicteto",
    "Quien se ríe de sí mismo nunca se queda sin cosas de las que reírse. — Epicteto",
    "La libertad es el único objetivo digno en la vida. — Epicteto",
    "Adjúntate a lo que es espiritualmente superior. — Epicteto",
    "Ponte a prueba, por el amor de Dios, en las cosas pequeñas. — Epicteto",

    // Febrero (32-59)
    "Sufrimos más a menudo en la imaginación que en la realidad. — Séneca",
    "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad. — Séneca",
    "No es que tengamos poco tiempo para vivir, sino que perdemos mucho. — Séneca",
    "Las dificultades fortalecen la mente, como el trabajo al cuerpo. — Séneca",
    "Quien es valiente es libre. — Séneca",
    "Mientras vivas, sigue aprendiendo a vivir. — Séneca",
    "Comienza ahora mismo a vivir, y cuenta cada día como una vida separada. — Séneca",
    "Toda crueldad brota de la debilidad. — Séneca",
    "Todo el futuro yace en la incertidumbre: vive inmediatamente. — Séneca",
    "Nadie tiene el poder de tener todo lo que quiere, pero sí tiene el poder de no querer lo que no tiene. — Séneca",
    "No se nos da una vida corta, sino que la hacemos corta. — Séneca",
    "Una gema no puede ser pulida sin fricción, ni un hombre perfeccionado sin pruebas. — Séneca",
    "Si realmente quieres escapar de las cosas que te acosan, lo que necesitas no es estar en un lugar diferente sino ser una persona diferente. — Séneca",
    "Conserva tus entusiasmos juveniles; podrás usarlos mejor cuando seas mayor. — Séneca",
    "Disfruta los placeres presentes de tal manera que no perjudiques los futuros. — Séneca",
    "A menudo sufrimos más por la aprensión que por la realidad. — Séneca",
    "El mayor remedio para la ira es el aplazamiento. — Séneca",
    "¿Qué necesidad hay de llorar por partes de la vida? Toda ella exige lágrimas. — Séneca",
    "Sufre más de lo necesario quien sufre antes de que sea necesario. — Séneca",
    "Mientras esperamos la vida, la vida pasa. — Séneca",
    "No importa lo que soportas, sino cómo lo soportas. — Séneca",
    "La vida es muy corta y ansiosa para quienes olvidan el pasado, descuidan el presente y temen el futuro. — Séneca",
    "Nadie puede perder lo que ya ha soltado. — Séneca",
    "El tiempo cura lo que la razón no puede. — Séneca",
    "El ocio sin libros es la muerte. — Séneca",
    "La ignorancia es la causa del miedo. — Séneca",
    "La verdadera felicidad es disfrutar el presente. — Séneca",
    "Con más frecuencia nos asustamos que nos lastiman; sufrimos más en la imaginación que en la realidad. — Séneca",

    // Marzo (60-90)
    "La clave es mantener compañía solo con personas que te eleven. — Epicteto",
    "No busques que todo suceda como deseas que suceda. — Epicteto",
    "Es imposible que un hombre aprenda lo que cree que ya sabe. — Epicteto",
    "Si deseas ser escritor, escribe. — Epicteto",
    "No busques que los eventos sucedan como deseas, sino desea que sucedan como suceden. — Epicteto",
    "El progreso no se logra por suerte o accidente, sino trabajando en ti mismo diariamente. — Epicteto",
    "Cuanto mayor es la dificultad, más gloria hay en superarla. — Epicteto",
    "Es sabio quien no se aflige por las cosas que no tiene. — Epicteto",
    "Cuando te ofendas por la falta de algún hombre, vuélvete a ti mismo. — Epicteto",
    "Solo los sabios son libres, y solo los virtuosos son sabios. — Epicteto",
    "Primero aprende el significado de lo que dices, y luego habla. — Epicteto",
    "Primero conoce quién eres, y luego adórnate en consecuencia. — Epicteto",
    "Si deseas ser bueno, comienza por creer que eres malvado. — Epicteto",
    "Tenemos dos oídos y una boca para poder escuchar el doble de lo que hablamos. — Epicteto",
    "No son los eventos los que perturban a las personas, sino sus juicios sobre ellos. — Epicteto",
    "Ponte a prueba, por el amor de Dios, en las cosas pequeñas. — Epicteto",
    "Quien está progresando ha aprendido que el deseo es para cosas buenas. — Epicteto",
    "El bien o el mal de un hombre yace dentro de su propia voluntad. — Epicteto",
    "Nada grande se crea de repente. — Epicteto",
    "En cada asunto, considera lo que precede y lo que sigue. — Epicteto",
    "No solo digas que has leído libros. Demuestra que a través de ellos has aprendido a pensar mejor. — Epicteto",
    "Lo que molesta a las personas no son las cosas en sí, sino sus juicios sobre estas cosas. — Epicteto",
    "No trates de parecer sabio ante los demás. — Epicteto",
    "No prediques a otros lo que deben comer, sino come como te conviene. — Epicteto",
    "Una persona educada es capaz de resistir y soportar dificultades. — Epicteto",
    "Nadie es libre si no es dueño de sí mismo. — Epicteto",
    "Ten cuidado de dejar a tus hijos bien instruidos en lugar de ricos. — Epicteto",
    "Se necesita más que un buen aspecto físico. Debes tener el corazón y el alma para acompañarlo. — Epicteto",
    "Cuando cierres tus puertas y hagas oscuridad dentro, recuerda nunca decir que estás solo. — Epicteto",
    "La condición y característica de una persona no instruida es esta: nunca espera beneficio de sí misma. — Epicteto",
    "Cuando estés a punto de emprender un proyecto, considera lo que precede y lo que sigue. — Epicteto",

    // Abril (91-120)
    "El obstáculo en el camino se convierte en el camino. — Marco Aurelio",
    "Nuestras acciones pueden ser impedidas, pero no puede haber impedimento para nuestras intenciones. — Marco Aurelio",
    "El valor de un hombre no es mayor que sus ambiciones. — Marco Aurelio",
    "Cava dentro. Dentro está el manantial del bien. — Marco Aurelio",
    "La pérdida no es más que cambio, y el cambio es el deleite de la Naturaleza. — Marco Aurelio",
    "Rechaza tu sensación de agravio y el agravio mismo desaparece. — Marco Aurelio",
    "La única riqueza que conservarás para siempre es la que has regalado. — Marco Aurelio",
    "Sin acciones aleatorias, ninguna sin principios subyacentes. — Marco Aurelio",
    "Vivir felizmente es un poder interior del alma. — Marco Aurelio",
    "La ira no puede ser deshonesta. — Marco Aurelio",
    "Porque tu propia fuerza es desigual para la tarea, no asumas que está más allá de los poderes del hombre. — Marco Aurelio",
    "No desprecies la muerte, sino acéptala, porque la naturaleza lo quiere como todo lo demás. — Marco Aurelio",
    "Quien vive en armonía consigo mismo vive en armonía con el universo. — Marco Aurelio",
    "Cuánto tiempo gana quien no mira a ver qué dice o hace su vecino. — Marco Aurelio",
    "A menudo me he preguntado cómo es que cada hombre se ama más a sí mismo que a todos los demás hombres. — Marco Aurelio",
    "En poco tiempo habrás olvidado todo; en poco tiempo todo te habrá olvidado a ti. — Marco Aurelio",
    "No dejes que tu mente se fije tanto en lo que te falta como en lo que ya tienes. — Marco Aurelio",
    "Mira hacia atrás en el pasado, con sus cambiantes imperios que surgieron y cayeron, y también puedes prever el futuro. — Marco Aurelio",
    "Nunca dejes que el futuro te perturbe. Lo enfrentarás, si es necesario, con las mismas armas de la razón. — Marco Aurelio",
    "Sin descuido en tus acciones. Sin confusión en tus palabras. — Marco Aurelio",
    "Nada tiene tanto poder para ampliar la mente como la capacidad de investigar sistemáticamente. — Marco Aurelio",
    "Juicio objetivo, ahora, en este mismo momento. — Marco Aurelio",
    "Pasa por este breve parche de tiempo en armonía con la naturaleza. — Marco Aurelio",
    "Recuerda que muy poco se necesita para tener una vida feliz. — Marco Aurelio",
    "Deja de vagar. No vas a releer tus breves notas. — Marco Aurelio",
    "Lo que no es bueno para el enjambre, tampoco lo es para la abeja. — Marco Aurelio",
    "El arte de vivir se parece más a la lucha que al baile. — Marco Aurelio",
    "La mente es la maestra de todo tipo de fortuna; actúa en ambos sentidos, siendo la causa de su propia felicidad y miseria. — Marco Aurelio",
    "El secreto de toda victoria reside en la organización de lo no obvio. — Marco Aurelio",
    "El universo es transformación; nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",

    // Mayo (121-150)
    "No estás obligado a formar ninguna opinión sobre este asunto. — Marco Aurelio",
    "La mente adapta y convierte a sus propios propósitos el obstáculo para nuestra acción. — Marco Aurelio",
    "Quita tu opinión, y se quita la queja. — Marco Aurelio",
    "La mejor respuesta a la ira es el silencio. — Marco Aurelio",
    "Recibe sin orgullo, suelta sin apego. — Marco Aurelio",
    "Piensa en la vida que has vivido hasta ahora como terminada y, como un hombre muerto, ve lo que queda como una bonificación. — Marco Aurelio",
    "El tiempo es un río de eventos pasajeros, y fuerte es su corriente. — Marco Aurelio",
    "Cualquier cosa que alguien haga o diga, debo ser bueno. — Marco Aurelio",
    "Cuando te levantes por la mañana, piensa en qué privilegio precioso es estar vivo. — Marco Aurelio",
    "Donde un hombre puede vivir, también puede vivir bien. — Marco Aurelio",
    "Siempre tienes la opción de no tener opinión. — Marco Aurelio",
    "Tu vida es lo que tus pensamientos la hacen. — Marco Aurelio",
    "Un malhechor es a menudo un hombre que ha dejado algo sin hacer. — Marco Aurelio",
    "Sé feliz pareciendo lo que realmente eres. — Marco Aurelio",
    "Porque algo te parece difícil, no pienses que es imposible. — Marco Aurelio",
    "No culpes a nadie. Corrige a las personas, si puedes. — Marco Aurelio",
    "La muerte nos sonríe a todos; todo lo que podemos hacer es sonreírle de vuelta. — Marco Aurelio",
    "Cada día trae sus propios regalos. — Marco Aurelio",
    "Todo lo que existe es de cierta manera la semilla de lo que será. — Marco Aurelio",
    "Quien no sabe lo que es el mundo, no sabe dónde está. — Marco Aurelio",
    "Si alguien puede convencerme y hacerme ver que no pienso o actúo correctamente, cambiaré gustosamente. — Marco Aurelio",
    "No es la muerte lo que un hombre debe temer, sino que debe temer nunca comenzar a vivir. — Marco Aurelio",
    "Que ningún acto sea hecho sin un propósito. — Marco Aurelio",
    "Nunca estimes nada como ventajoso para ti que te haga romper tu palabra. — Marco Aurelio",
    "Ningún hombre es feliz si no se cree así. — Marco Aurelio",
    "Nada le sucede a ningún hombre que no esté formado por la naturaleza para soportar. — Marco Aurelio",
    "Nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",
    "La pobreza es la madre del crimen. — Marco Aurelio",
    "Recuerda esto: hay una dignidad y proporción adecuadas que deben observarse. — Marco Aurelio",
    "La felicidad de tu vida depende de la calidad de tus pensamientos. — Marco Aurelio",

    // Junio (151-180)
    "Confínate al presente. — Marco Aurelio",
    "El presente es todo lo que pueden renunciar, ya que eso es todo lo que tienes. — Marco Aurelio",
    "Cada uno de nosotros vive solo ahora, este breve instante. — Marco Aurelio",
    "Date un regalo: el momento presente. — Marco Aurelio",
    "En la vida de un hombre, su tiempo es solo un momento. — Marco Aurelio",
    "Deja que las cosas futuras perturben a quienes puedan verse afectados por ellas. — Marco Aurelio",
    "Vive como si estuvieras viviendo por segunda vez. — Marco Aurelio",
    "Nada me pertenece excepto el presente. — Marco Aurelio",
    "El momento presente es todo lo que alguna vez tienes. — Marco Aurelio",
    "Hoy escapé de la ansiedad. O no, la descarté, porque estaba dentro de mí. — Marco Aurelio",
    "No actúes como si tuvieras diez mil años para desperdiciar. — Marco Aurelio",
    "Porque el presente es la única cosa de la que un hombre puede ser privado. — Marco Aurelio",
    "Quien vive en el presente vive en la eternidad. — Marco Aurelio",
    "Cuántos junto con los que vine al mundo ya han salido de él. — Marco Aurelio",
    "No es el futuro lo que te pesa, sino el presente. — Marco Aurelio",
    "No dejes que tu mente se cargue con el pasado o el futuro. — Marco Aurelio",
    "Vive cada día como si fuera tu último. — Marco Aurelio",
    "No hables más sobre el tipo de hombre que un buen hombre debe ser, sino sé así. — Marco Aurelio",
    "El tiempo presente es de la mayor importancia. — Marco Aurelio",
    "Aunque te rompas el corazón, los hombres seguirán como antes. — Marco Aurelio",
    "Mañana es nada, hoy es demasiado tarde; el bueno vivió ayer. — Marco Aurelio",
    "Un hombre debe mantenerse erguido, no ser mantenido erguido por otros. — Marco Aurelio",
    "Sé como el acantilado contra el cual las olas rompen continuamente. — Marco Aurelio",
    "La muerte es una liberación de las impresiones de los sentidos. — Marco Aurelio",
    "Todo lo que sucede sucede como debe. — Marco Aurelio",
    "Quien teme a la muerte teme ya sea la pérdida de sensación o un tipo diferente de sensación. — Marco Aurelio",
    "Si no es correcto, no lo hagas; si no es verdad, no lo digas. — Marco Aurelio",
    "Está en tu poder retirarte cuando lo desees. — Marco Aurelio",
    "Quita la opinión, y ningún hombre se sentirá agraviado. — Marco Aurelio",
    "Nunca dejes que el futuro te perturbe. — Marco Aurelio",

    // Julio (181-210)
    "No malgastes más tiempo discutiendo sobre cómo debe ser un buen hombre. Sé uno. — Marco Aurelio",
    "La virtud es el único bien. — Séneca",
    "El hombre bueno es amigo de los dioses. — Epicteto",
    "La virtud no es más que razón correcta. — Séneca",
    "El hombre sabio está contento consigo mismo. — Séneca",
    "La virtud es su propia recompensa. — Séneca",
    "Un buen carácter es la única garantía de felicidad eterna. — Séneca",
    "La sabiduría no permite que nada sea bueno que no lo sea para siempre. — Séneca",
    "Ningún mal es honorable; pero la muerte es honorable; por lo tanto, la muerte no es mal. — Séneca",
    "La mayor riqueza es una pobreza de deseos. — Séneca",
    "El primer paso en la salvación de una persona es el conocimiento de su pecado. — Séneca",
    "Deberíamos cada noche llamarnos a rendir cuentas. — Séneca",
    "Una mente buena posee un reino. — Séneca",
    "El mayor remedio para la ira es el aplazamiento. — Séneca",
    "La ira, si no se restringe, es frecuentemente más perjudicial para nosotros que la lesión que la provoca. — Séneca",
    "Quien no previene un crimen cuando puede, lo alienta. — Séneca",
    "Es la calidad más que la cantidad lo que importa. — Séneca",
    "Ningún hombre fue sabio por casualidad. — Séneca",
    "La mente que está ansiosa por eventos futuros es miserable. — Séneca",
    "Dondequiera que haya un ser humano, hay una oportunidad para la bondad. — Séneca",
    "Un hombre es tan miserable como piensa que es. — Séneca",
    "Quien es valiente es libre. — Séneca",
    "Es un camino difícil el que lleva a las alturas de la grandeza. — Séneca",
    "Ningún hombre puede tener una vida pacífica que piense demasiado en prolongarla. — Séneca",
    "A los dispuestos, el destino los guía. A los renuentes, el destino los arrastra. — Séneca",
    "La sabiduría no se muestra tanto en el precepto como en la vida. — Séneca",
    "Una gema no puede ser pulida sin fricción, ni un hombre perfeccionado sin pruebas. — Séneca",
    "Quien tiene gran poder debe usarlo con ligereza. — Séneca",
    "No es el hombre que tiene muy poco, sino el hombre que anhela más, el que es pobre. — Séneca",
    "Ninguna propensión maligna del corazón humano es tan poderosa que no pueda ser sometida por la disciplina. — Séneca",

    // Agosto (211-240)
    "Deja que tus deseos sean gobernados por la razón. — Cicerón",
    "La libertad no se obtiene por el pleno disfrute de lo deseado. — Epicteto",
    "No es el hombre que tiene muy poco, sino el hombre que anhela más, el que es pobre. — Séneca",
    "Si deseas ser bueno, comienza por creer que eres malvado. — Epicteto",
    "La riqueza no consiste en tener grandes posesiones, sino en tener pocos deseos. — Epicteto",
    "Cuanto mayor es la dificultad, más gloria hay en superarla. — Epicteto",
    "Es sabio quien no se aflige por las cosas que no tiene. — Epicteto",
    "Primero dite a ti mismo lo que serías; y luego haz lo que tienes que hacer. — Epicteto",
    "Si quieres mejorar, estate dispuesto a que te consideren tonto. — Epicteto",
    "Nada grande se crea de repente. — Epicteto",
    "La clave es mantener compañía solo con personas que te eleven. — Epicteto",
    "Tenemos dos oídos y una boca para poder escuchar el doble de lo que hablamos. — Epicteto",
    "No solo digas que has leído libros. Demuestra que a través de ellos has aprendido a pensar mejor. — Epicteto",
    "No trates de parecer sabio ante los demás. — Epicteto",
    "Primero conoce quién eres, y luego adórnate en consecuencia. — Epicteto",
    "Es imposible que un hombre aprenda lo que cree que ya sabe. — Epicteto",
    "La condición y característica de una persona no instruida es esta: nunca espera beneficio de sí misma. — Epicteto",
    "Solo los educados son libres. — Epicteto",
    "Cuando te ofendas por la falta de algún hombre, vuélvete a ti mismo. — Epicteto",
    "Quien está progresando ha aprendido que el deseo es para cosas buenas. — Epicteto",
    "El bien o el mal de un hombre yace dentro de su propia voluntad. — Epicteto",
    "Ponte a prueba, por el amor de Dios, en las cosas pequeñas. — Epicteto",
    "Una persona educada es capaz de resistir y soportar dificultades. — Epicteto",
    "Ten cuidado de dejar a tus hijos bien instruidos en lugar de ricos. — Epicteto",
    "Quien se ríe de sí mismo nunca se queda sin cosas de las que reírse. — Epicteto",
    "Se necesita más que un buen aspecto físico. Debes tener el corazón y el alma para acompañarlo. — Epicteto",
    "Cuando cierres tus puertas y hagas oscuridad dentro, recuerda nunca decir que estás solo. — Epicteto",
    "En cada asunto, considera lo que precede y lo que sigue. — Epicteto",
    "No busques que los eventos sucedan como deseas, sino desea que sucedan como suceden. — Epicteto",
    "Primero aprende el significado de lo que dices, y luego habla. — Epicteto",

    // Septiembre (241-270)
    "Acepta las cosas a las que el destino te ata. — Marco Aurelio",
    "No exijas que las cosas sucedan como deseas, sino desea que sucedan como suceden. — Epicteto",
    "El destino guía a los dispuestos y arrastra a los renuentes. — Séneca",
    "Todo lo que sucede sucede como debe. — Marco Aurelio",
    "Si estás angustiado por algo externo, el dolor no se debe a la cosa en sí. — Marco Aurelio",
    "Lo que se interpone en el camino se convierte en el camino. — Marco Aurelio",
    "El universo es cambio; nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",
    "La pérdida no es más que cambio, y el cambio es el deleite de la Naturaleza. — Marco Aurelio",
    "Rechaza tu sensación de agravio y el agravio mismo desaparece. — Marco Aurelio",
    "Sin acciones aleatorias, ninguna sin principios subyacentes. — Marco Aurelio",
    "Quien vive en armonía consigo mismo vive en armonía con el universo. — Marco Aurelio",
    "Mira hacia atrás en el pasado, con sus cambiantes imperios que surgieron y cayeron. — Marco Aurelio",
    "Nunca dejes que el futuro te perturbe. Lo enfrentarás con las mismas armas de la razón. — Marco Aurelio",
    "Juicio objetivo, ahora, en este mismo momento. — Marco Aurelio",
    "Pasa por este breve parche de tiempo en armonía con la naturaleza. — Marco Aurelio",
    "El arte de vivir se parece más a la lucha que al baile. — Marco Aurelio",
    "La mente es la maestra de todo tipo de fortuna. — Marco Aurelio",
    "El universo es transformación; nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",
    "Piensa en la vida que has vivido hasta ahora como terminada y, como un hombre muerto, ve lo que queda como una bonificación. — Marco Aurelio",
    "El tiempo es un río de eventos pasajeros, y fuerte es su corriente. — Marco Aurelio",
    "Cualquier cosa que alguien haga o diga, debo ser bueno. — Marco Aurelio",
    "Cuando te levantes por la mañana, piensa en qué privilegio precioso es estar vivo. — Marco Aurelio",
    "Donde un hombre puede vivir, también puede vivir bien. — Marco Aurelio",
    "Siempre tienes la opción de no tener opinión. — Marco Aurelio",
    "Tu vida es lo que tus pensamientos la hacen. — Marco Aurelio",
    "No culpes a nadie. Corrige a las personas, si puedes. — Marco Aurelio",
    "La muerte nos sonríe a todos; todo lo que podemos hacer es sonreírle de vuelta. — Marco Aurelio",
    "Cada día trae sus propios regalos. — Marco Aurelio",
    "Todo lo que existe es de cierta manera la semilla de lo que será. — Marco Aurelio",
    "Si alguien puede convencerme y hacerme ver que no pienso o actúo correctamente, cambiaré gustosamente. — Marco Aurelio",

    // Octubre (271-300)
    "Piensa en ti mismo como muerto. Has vivido tu vida. Ahora toma lo que queda y vívela adecuadamente. — Marco Aurelio",
    "Preparemos nuestras mentes como si hubiéramos llegado al final mismo de la vida. — Séneca",
    "No puedo escapar de la muerte, pero al menos puedo escapar del miedo a ella. — Epicteto",
    "No es la muerte lo que un hombre debe temer, sino que debe temer nunca comenzar a vivir. — Marco Aurelio",
    "La muerte es una liberación de las impresiones de los sentidos. — Marco Aurelio",
    "Quien teme a la muerte teme ya sea la pérdida de sensación o un tipo diferente de sensación. — Marco Aurelio",
    "En poco tiempo habrás olvidado todo; en poco tiempo todo te habrá olvidado a ti. — Marco Aurelio",
    "No dejes que tu mente se cargue con el pasado o el futuro. — Marco Aurelio",
    "Ningún hombre puede tener una vida pacífica que piense demasiado en prolongarla. — Séneca",
    "El presente es todo lo que pueden renunciar, ya que eso es todo lo que tienes. — Marco Aurelio",
    "Hoy escapé de la ansiedad. O no, la descarté, porque estaba dentro de mí. — Marco Aurelio",
    "No actúes como si tuvieras diez mil años para desperdiciar. — Marco Aurelio",
    "Porque el presente es la única cosa de la que un hombre puede ser privado. — Marco Aurelio",
    "Cuántos junto con los que vine al mundo ya han salido de él. — Marco Aurelio",
    "No es el futuro lo que te pesa, sino el presente. — Marco Aurelio",
    "Vive cada día como si fuera tu último. — Marco Aurelio",
    "No hables más sobre el tipo de hombre que un buen hombre debe ser, sino sé así. — Marco Aurelio",
    "El tiempo presente es de la mayor importancia. — Marco Aurelio",
    "Aunque te rompas el corazón, los hombres seguirán como antes. — Marco Aurelio",
    "Mañana es nada, hoy es demasiado tarde; el bueno vivió ayer. — Marco Aurelio",
    "Un hombre debe mantenerse erguido, no ser mantenido erguido por otros. — Marco Aurelio",
    "Sé como el acantilado contra el cual las olas rompen continuamente. — Marco Aurelio",
    "Todo lo que sucede sucede como debe. — Marco Aurelio",
    "Si no es correcto, no lo hagas; si no es verdad, no lo digas. — Marco Aurelio",
    "Está en tu poder retirarte cuando lo desees. — Marco Aurelio",
    "Quita la opinión, y ningún hombre se sentirá agraviado. — Marco Aurelio",
    "Nunca dejes que el futuro te perturbe. — Marco Aurelio",
    "Ningún hombre es feliz si no se cree así. — Marco Aurelio",
    "Nada le sucede a ningún hombre que no esté formado por la naturaleza para soportar. — Marco Aurelio",
    "Nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",

    // Noviembre (301-330)
    "La sabiduría es la única libertad. — Séneca",
    "Saber envejecer es la obra maestra de la sabiduría. — Henri-Frédéric Amiel",
    "El hombre sabio está libre de restricciones. — Musonio Rufo",
    "La sabiduría no permite que nada sea bueno que no lo sea para siempre. — Séneca",
    "Ningún mal es honorable; pero la muerte es honorable; por lo tanto, la muerte no es mal. — Séneca",
    "La mayor riqueza es una pobreza de deseos. — Séneca",
    "El primer paso en la salvación de una persona es el conocimiento de su pecado. — Séneca",
    "Deberíamos cada noche llamarnos a rendir cuentas. — Séneca",
    "Una mente buena posee un reino. — Séneca",
    "El mayor remedio para la ira es el aplazamiento. — Séneca",
    "La ira, si no se restringe, es frecuentemente más perjudicial para nosotros que la lesión que la provoca. — Séneca",
    "Quien no previene un crimen cuando puede, lo alienta. — Séneca",
    "Es la calidad más que la cantidad lo que importa. — Séneca",
    "Ningún hombre fue sabio por casualidad. — Séneca",
    "La mente que está ansiosa por eventos futuros es miserable. — Séneca",
    "Dondequiera que haya un ser humano, hay una oportunidad para la bondad. — Séneca",
    "Un hombre es tan miserable como piensa que es. — Séneca",
    "Quien es valiente es libre. — Séneca",
    "Es un camino difícil el que lleva a las alturas de la grandeza. — Séneca",
    "Ningún hombre puede tener una vida pacífica que piense demasiado en prolongarla. — Séneca",
    "A los dispuestos, el destino los guía. A los renuentes, el destino los arrastra. — Séneca",
    "La sabiduría no se muestra tanto en el precepto como en la vida. — Séneca",
    "Una gema no puede ser pulida sin fricción, ni un hombre perfeccionado sin pruebas. — Séneca",
    "Quien tiene gran poder debe usarlo con ligereza. — Séneca",
    "No es el hombre que tiene muy poco, sino el hombre que anhela más, el que es pobre. — Séneca",
    "Ninguna propensión maligna del corazón humano es tan poderosa que no pueda ser sometida por la disciplina. — Séneca",
    "El hombre sabio está contento consigo mismo. — Séneca",
    "La virtud es su propia recompensa. — Séneca",
    "Un buen carácter es la única garantía de felicidad eterna. — Séneca",
    "La virtud no es más que razón correcta. — Séneca",

    // Diciembre (331-365)
    "Quien vive en armonía consigo mismo vive en armonía con el universo. — Marco Aurelio",
    "La paz está en guardar silencio cuando no tienes nada útil que decir. — Musonio Rufo",
    "Nada es tan conducente a la grandeza de mente como la capacidad de examinar sistemáticamente. — Séneca",
    "La mejor venganza es no ser como tu enemigo. — Marco Aurelio",
    "Muy poco se necesita para tener una vida feliz. — Marco Aurelio",
    "Acepta lo que venga a ti tejido en el patrón de tu destino. — Marco Aurelio",
    "El alma se tiñe del color de sus pensamientos. — Marco Aurelio",
    "Todo lo que oímos es una opinión, no un hecho. — Marco Aurelio",
    "En ninguna parte puede el hombre encontrar un retiro más tranquilo que en su propia alma. — Marco Aurelio",
    "La vida es corta; el fruto de esta vida es un buen carácter. — Marco Aurelio",
    "Sé tolerante con los demás y estricto contigo mismo. — Marco Aurelio",
    "El universo es cambio; nuestra vida es lo que nuestros pensamientos la hacen. — Marco Aurelio",
    "Mira bien dentro de ti mismo; allí hay una fuente de fortaleza. — Marco Aurelio",
    "Nada le sucede a nadie que no pueda soportar. — Marco Aurelio",
    "La primera regla es mantener un espíritu sereno. — Marco Aurelio",
    "Realiza cada acto de tu vida como si fuera el último. — Marco Aurelio",
    "Si no es correcto, no lo hagas. Si no es verdad, no lo digas. — Marco Aurelio",
    "Ahora es el momento de aprender verdaderamente quién eres. — Marco Aurelio",
    "Deja que los hombres vean, que conozcan a un hombre verdadero. — Marco Aurelio",
    "Eres un alma pequeña que carga un cadáver. — Epicteto",
    "No expliques tu filosofía. Encárnala. — Epicteto",
    "La riqueza no consiste en tener grandes posesiones, sino en tener pocos deseos. — Epicteto",
    "Primero dite a ti mismo lo que serías; y luego haz lo que tienes que hacer. — Epicteto",
    "Ningún hombre es libre si no es dueño de sí mismo. — Epicteto",
    "Las circunstancias no hacen al hombre, solo lo revelan. — Epicteto",
    "No es lo que te sucede, sino cómo reaccionas lo que importa. — Epicteto",
    "Solo los educados son libres. — Epicteto",
    "Si quieres mejorar, estate dispuesto a que te consideren tonto. — Epicteto",
    "Quien se ríe de sí mismo nunca se queda sin cosas de las que reírse. — Epicteto",
    "La libertad es el único objetivo digno en la vida. — Epicteto",
    "Adjúntate a lo que es espiritualmente superior. — Epicteto",
    "Ponte a prueba, por el amor de Dios, en las cosas pequeñas. — Epicteto",
    "Sufrimos más a menudo en la imaginación que en la realidad. — Séneca",
    "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad. — Séneca",
    "No es que tengamos poco tiempo para vivir, sino que perdemos mucho. — Séneca"
]
